# Generated by Django 3.2.4 on 2021-06-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
