# Generated by Django 3.2.4 on 2021-06-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210627_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
