# Generated by Django 3.2.4 on 2021-06-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.AddField(
            model_name='place',
            name='priority',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place'),
        ),
    ]
