# Generated by Django 3.2.4 on 2021-06-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210629_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='priority',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='places.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'priority')},
        ),
    ]
