# Generated by Django 3.2.4 on 2021-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210629_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='json_file',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='priority',
            field=models.PositiveIntegerField(),
        ),
    ]
