# Generated by Django 3.2.4 on 2021-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='json_file',
            field=models.CharField(max_length=100),
        ),
    ]
